name: Full test on pull request to main

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  full-stack-test:
    runs-on: ubuntu-latest

    env:
      SENDER_MAIL_PORT: ${{ secrets.SENDER_MAIL_PORT }}
      SENDER_MAIL_ADDRESS: ${{ secrets.SENDER_MAIL_ADDRESS }}
      SENDER_MAIL_PASSWORD: ${{ secrets.SENDER_MAIL_PASSWORD }}
      GOOGLE_AUTH_CLIENT_ID: ${{ secrets.GOOGLE_AUTH_CLIENT_ID }}

      # MinIO variables (override the values within application.properties)
      MINIO_URL: "https://localhost:9000"
      MINIO_SSL_INSECURE: "true"

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: Frict
          MYSQL_ROOT_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Start MinIO and Create Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ROOT_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_ROOT_PASSWORD }}
          AWS_REGION: us-east-1
        run: |
          mkdir -p /tmp/minio_certs
          cp -r $(pwd)/docker/minio_https/certs/* /tmp/minio_certs/
          
          docker run -d \
            -p 9000:9000 \
            -p 9001:9001 \
            --name minio \
            -v /tmp/minio_certs:/root/.minio/certs \
            -e MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }} \
            -e MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }} \
            minio/minio server /data --console-address ":9001"
          
          sleep 5
          aws --endpoint-url https://localhost:9000 --no-verify-ssl s3 mb s3://${{ secrets.MINIO_BUCKET_NAME }}


      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'


      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json


      - name: Run Backend Unit, API and Integration tests
        working-directory: backend
        run: |
          mvn test -Dtest='com.tfg.backend.unit.**'
          mvn test -Dtest='com.tfg.backend.api.**'
          mvn test -Dtest='com.tfg.backend.integration.**'


      - name: Install Frontend Dependencies
        working-directory: frontend
        run: |
          npm ci
          npm install -g @angular/cli


      - name: Run Client Unit Tests
        working-directory: frontend
        run: ng test --watch=false --browsers=ChromeHeadlessNoSandbox


      - name: Start Angular for E2E Tests
        working-directory: frontend
        run: ng serve --proxy-config proxy-test.conf.json &


      - name: Run E2E Tests
        working-directory: backend
        run: mvn test -Dtest='com.tfg.backend.e2e.**'