name: Full test on pull request to main

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  server-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: Frict
          MYSQL_ROOT_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run server unit tests
        run: mvn test -Dtest=com.tfg.backend.unit.ProductServiceTest

      - name: Run server integration tests
        run: mvn test -Dtest=com.tfg.backend.integration.*Test

      - name: Run server system tests
        run: mvn test -Dtest=com.tfg.backend.e2e.ProductSystemApiTest


  client-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: Frict
          MYSQL_ROOT_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Angular CLI
        run: npm install -g @angular/cli

      - name: Install project dependencies
        run: npm ci
        working-directory: frontend

      - name: Run client unit tests
        run: ng test --watch=false --browsers=ChromeHeadlessNoSandbox
        working-directory: frontend

      - name: Start Angular project
        run: ng serve --proxy-config proxy-test.conf.json &
        working-directory: frontend

      - name: Run client system tests
        run: mvn test -Dtest=com.tfg.backend.e2e.ProductSystemUITest
        working-directory: backend