name: Full test on pull request to main

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  full-stack-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: Frict
          MYSQL_ROOT_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      minio:
        image: bitnami/minio:latest
        env:
          MINIO_ROOT_USER: ${{ secrets.MINIO_ROOT_USER }}
          MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_ROOT_PASSWORD }}
        ports:
          - 9000:9000
          - 9001:9001

    steps:
      - uses: actions/checkout@v4

      - name: Create MinIO Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ROOT_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_ROOT_PASSWORD }}
          AWS_REGION: us-east-1
        run: |
          sleep 5
          aws --endpoint-url http://localhost:9000 s3 mb s3://${{ secrets.MINIO_BUCKET_NAME }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Run Backend Unit & Integration Tests
        working-directory: backend
        run: |
          mvn test -Dtest=com.tfg.backend.unit.*Test
          mvn test -Dtest=com.tfg.backend.integration.*Test
          mvn test -Dtest=com.tfg.backend.e2e.ProductSystemApiTest

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: |
          npm ci
          npm install -g @angular/cli

      - name: Run Client Unit Tests
        working-directory: frontend
        run: ng test --watch=false --browsers=ChromeHeadlessNoSandbox

      - name: Start Angular for E2E
        working-directory: frontend
        run: ng serve --proxy-config proxy-test.conf.json &

      - name: Run E2E System Tests
        working-directory: backend
        run: mvn test -Dtest=com.tfg.backend.e2e.ProductSystemUITest